//! The system clipboard, for the history: what's on it, which app is in
//! front, and putting clips back. On macOS this talks to NSPasteboard
//! directly (text, images, files, and the markers password managers set);
//! elsewhere it falls back to text only through `arboard`.

use std::path::PathBuf;

/// What was on the clipboard at one moment.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Snapshot {
    /// Marked as private or temporary (passwords, one-time codes): never record.
    pub concealed: bool,
    pub files: Vec<PathBuf>,
    pub text: Option<String>,
    /// The image, normalised to PNG (so the same picture always hashes the same).
    pub image_png: Option<Vec<u8>>,
}

/// Pasteboard types that mark content as not to be recorded
/// (see nspasteboard.org), and password managers' own markers.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub const CONCEALED_TYPES: [&str; 6] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
];

/// Apps whose copies are never recorded, whatever they mark them as.
pub const IGNORED_APPS: [&str; 7] = [
    "com.apple.Passwords",
    "com.apple.keychainaccess",
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.bitwarden.desktop",
    "org.keepassxc.keepassxc",
    "com.dashlane.dashlanephonefinal",
];

pub use xpress_core::clipboard::Part;

/// Decode any image the `image` crate reads and re-encode it as PNG.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub fn normalise_png(bytes: &[u8]) -> Option<Vec<u8>> {
    let img = image::load_from_memory(bytes).ok()?;
    let mut out = Vec::new();
    img.to_rgba8()
        .write_to(&mut std::io::Cursor::new(&mut out), image::ImageFormat::Png)
        .ok()?;
    Some(out)
}

#[cfg(target_os = "macos")]
mod imp {
    use super::*;
    use objc2::rc::Retained;
    use objc2_app_kit::{
        NSPasteboard, NSPasteboardTypeFileURL, NSPasteboardTypePNG, NSPasteboardTypeString,
        NSPasteboardTypeTIFF, NSWorkspace,
    };
    use objc2_foundation::NSURL;

    fn general() -> Retained<NSPasteboard> {
        NSPasteboard::generalPasteboard()
    }

    /// Increases every time anything is copied.
    pub fn change_count() -> isize {
        general().changeCount()
    }

    pub fn read() -> Snapshot {
        read_from(&general())
    }

    pub fn write(parts: &[Part]) -> bool {
        xpress_core::clipboard::write(parts)
    }

    fn read_from(pb: &NSPasteboard) -> Snapshot {
        objc2::rc::autoreleasepool(|_| {
            let types: Vec<String> = pb
                .types()
                .map(|t| t.iter().map(|t| t.to_string()).collect())
                .unwrap_or_default();
            if types.iter().any(|t| CONCEALED_TYPES.contains(&t.as_str())) {
                return Snapshot {
                    concealed: true,
                    ..Default::default()
                };
            }

            let files: Vec<PathBuf> = pb
                .pasteboardItems()
                .map(|items| {
                    items
                        .iter()
                        .filter_map(|item| item.stringForType(unsafe { NSPasteboardTypeFileURL }))
                        .filter_map(|s| NSURL::URLWithString(&s))
                        .filter_map(|url| url.path())
                        .map(|p| PathBuf::from(p.to_string()))
                        .collect()
                })
                .unwrap_or_default();
            let text = pb
                .stringForType(unsafe { NSPasteboardTypeString })
                .map(|s| s.to_string());
            let image_png = [unsafe { NSPasteboardTypePNG }, unsafe {
                NSPasteboardTypeTIFF
            }]
            .into_iter()
            .find_map(|t| pb.dataForType(t))
            .and_then(|data| normalise_png(&data.to_vec()));
            Snapshot {
                concealed: false,
                files,
                text,
                image_png,
            }
        })
    }

    /// The name and bundle id of the app in front.
    pub fn frontmost_app() -> (Option<String>, Option<String>) {
        let app = NSWorkspace::sharedWorkspace().frontmostApplication();
        (
            app.as_ref()
                .and_then(|a| a.localizedName())
                .map(|s| s.to_string()),
            app.as_ref()
                .and_then(|a| a.bundleIdentifier())
                .map(|s| s.to_string()),
        )
    }

    /// Against a private pasteboard, so the tests never touch your clipboard.
    #[cfg(test)]
    mod tests {
        use super::*;
        use objc2_app_kit::NSPasteboardTypeHTML;
        use objc2_foundation::NSString;
        use xpress_core::clipboard::write_to;

        struct Private(Retained<NSPasteboard>);
        impl Drop for Private {
            fn drop(&mut self) {
                // Not in the bindings; frees the private pasteboard's name.
                unsafe { objc2::msg_send![&*self.0, releaseGlobally] }
            }
        }
        fn private() -> Private {
            Private(NSPasteboard::pasteboardWithUniqueName())
        }

        #[test]
        fn text_round_trip_and_change_count() {
            let pb = private();
            let before = pb.0.changeCount();
            assert!(write_to(&pb.0, &[Part::Text("héllo ✓".into())]));
            assert!(pb.0.changeCount() > before);
            let snap = read_from(&pb.0);
            assert_eq!(snap.text.as_deref(), Some("héllo ✓"));
            assert!(!snap.concealed && snap.files.is_empty() && snap.image_png.is_none());
        }

        #[test]
        fn image_round_trip_is_normalised() {
            let pb = private();
            let mut jpeg = Vec::new();
            image::RgbImage::from_pixel(8, 6, image::Rgb([200, 30, 30]))
                .write_to(
                    &mut std::io::Cursor::new(&mut jpeg),
                    image::ImageFormat::Png,
                )
                .unwrap();
            assert!(write_to(&pb.0, &[Part::Png(jpeg)]));
            let png = read_from(&pb.0).image_png.unwrap();
            let img = image::load_from_memory(&png).unwrap();
            assert_eq!((img.width(), img.height()), (8, 6));
            // Reading the same picture again gives the same bytes (one clip).
            assert!(write_to(&pb.0, &[Part::Png(png.clone())]));
            assert_eq!(read_from(&pb.0).image_png.unwrap(), png);
        }

        #[test]
        fn files_round_trip() {
            let pb = private();
            let dir = tempfile::tempdir().unwrap();
            let a = dir.path().join("a report.pdf");
            let b = dir.path().join("b.txt");
            std::fs::write(&a, b"x").unwrap();
            std::fs::write(&b, b"y").unwrap();
            assert!(write_to(
                &pb.0,
                &[Part::File(a.clone()), Part::File(b.clone())]
            ));
            let files = read_from(&pb.0).files;
            let canon = |p: &PathBuf| std::fs::canonicalize(p).unwrap();
            assert_eq!(
                files.iter().map(canon).collect::<Vec<_>>(),
                [canon(&a), canon(&b)]
            );
        }

        #[test]
        fn parts_go_on_together() {
            let pb = private();
            let mut png = Vec::new();
            image::RgbImage::from_pixel(2, 2, image::Rgb([1, 2, 3]))
                .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
                .unwrap();
            assert!(write_to(
                &pb.0,
                &[
                    Part::Text("Hello".into()),
                    Part::Png(png),
                    Part::Text("https://kwhorne.com".into())
                ]
            ));
            let snap = read_from(&pb.0);
            assert_eq!(snap.text.as_deref(), Some("Hello\nhttps://kwhorne.com"));
            assert!(snap.image_png.is_some());
            let html =
                pb.0.stringForType(unsafe { NSPasteboardTypeHTML })
                    .unwrap()
                    .to_string();
            assert!(html.contains("<p>Hello</p>"));
            assert!(html.contains("data:image/png;base64,"));
            assert!(html.contains("<a href=\"https://kwhorne.com\">"));
        }

        #[test]
        fn concealed_content_is_flagged() {
            let pb = private();
            pb.0.clearContents();
            pb.0.setString_forType(&NSString::from_str("hunter2"), unsafe {
                NSPasteboardTypeString
            });
            pb.0.setString_forType(
                &NSString::from_str(""),
                &NSString::from_str("org.nspasteboard.ConcealedType"),
            );
            let snap = read_from(&pb.0);
            assert!(snap.concealed);
            assert!(snap.text.is_none(), "nothing is read from it");
        }
    }
}

/// A cheap fingerprint of an image: its size and a sample of its pixels
/// (hashing every byte of a large screenshot twice a second would be wasteful).
#[cfg_attr(target_os = "macos", allow(dead_code))]
pub fn image_signature(width: usize, height: usize, rgba: &[u8]) -> u64 {
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    (width, height, rgba.len()).hash(&mut h);
    let step = (rgba.len() / 4096).max(1);
    for byte in rgba.iter().step_by(step) {
        byte.hash(&mut h);
    }
    h.finish()
}

/// Encode RGBA pixels as PNG.
#[cfg_attr(target_os = "macos", allow(dead_code))]
fn rgba_png(width: usize, height: usize, rgba: Vec<u8>) -> Option<Vec<u8>> {
    let img = image::RgbaImage::from_raw(width as u32, height as u32, rgba)?;
    let mut out = Vec::new();
    img.write_to(&mut std::io::Cursor::new(&mut out), image::ImageFormat::Png)
        .ok()?;
    Some(out)
}

/// Linux and others, through `arboard` (X11, and Wayland compositors with the
/// data-control protocol). There's no change counter, so the clipboard's
/// content is fingerprinted; images only every second check, and only when
/// there's no text or files.
#[cfg(not(target_os = "macos"))]
mod imp {
    use super::*;
    use std::hash::{Hash, Hasher};
    use std::sync::atomic::{AtomicU32, AtomicU64, Ordering};

    static CHECKS: AtomicU32 = AtomicU32::new(0);
    static IMAGE: AtomicU64 = AtomicU64::new(0);

    pub fn change_count() -> isize {
        let Ok(mut clipboard) = arboard::Clipboard::new() else {
            return 0;
        };
        let text = clipboard.get_text().ok();
        let files = clipboard.get().file_list().ok().filter(|f| !f.is_empty());
        let mut h = std::collections::hash_map::DefaultHasher::new();
        (&text, &files).hash(&mut h);
        if text.is_none() && files.is_none() {
            if CHECKS.fetch_add(1, Ordering::Relaxed).is_multiple_of(2) {
                let signature = clipboard
                    .get_image()
                    .map(|img| image_signature(img.width, img.height, &img.bytes))
                    .unwrap_or(0);
                IMAGE.store(signature, Ordering::Relaxed);
            }
            IMAGE.load(Ordering::Relaxed).hash(&mut h);
        }
        h.finish() as isize
    }

    pub fn read() -> Snapshot {
        let Ok(mut clipboard) = arboard::Clipboard::new() else {
            return Snapshot::default();
        };
        let text = clipboard.get_text().ok();
        let files = clipboard.get().file_list().unwrap_or_default();
        let image_png = if text.is_none() && files.is_empty() {
            clipboard
                .get_image()
                .ok()
                .and_then(|img| rgba_png(img.width, img.height, img.bytes.into_owned()))
        } else {
            None
        };
        Snapshot {
            concealed: false,
            files,
            text,
            image_png,
        }
    }

    pub fn frontmost_app() -> (Option<String>, Option<String>) {
        (None, None)
    }

    pub fn write(parts: &[Part]) -> bool {
        let composed = xpress_core::clipboard::compose(parts);
        let Ok(mut clipboard) = arboard::Clipboard::new() else {
            return false;
        };
        if !composed.files.is_empty() {
            return clipboard.set().file_list(&composed.files).is_ok();
        }
        if let Some(html) = composed.html {
            // Both the same type, as arboard wants.
            let alt = (!composed.text.is_empty()).then(|| composed.text.clone());
            return clipboard.set().html(html, alt).is_ok();
        }
        if !composed.text.is_empty() {
            return clipboard.set_text(composed.text).is_ok();
        }
        let Some(png) = composed.png else {
            return false;
        };
        let Ok(img) = image::load_from_memory(&png) else {
            return false;
        };
        let rgba = img.to_rgba8();
        let data = arboard::ImageData {
            width: rgba.width() as usize,
            height: rgba.height() as usize,
            bytes: rgba.into_raw().into(),
        };
        clipboard.set_image(data).is_ok()
    }
}

pub use imp::{change_count, frontmost_app, read, write};

#[cfg(test)]
mod portable_tests {
    use super::*;

    #[test]
    fn image_fingerprints() {
        let a = vec![7u8; 400 * 300 * 4];
        let mut b = a.clone();
        assert_eq!(image_signature(400, 300, &a), image_signature(400, 300, &b));
        b[0] = 8;
        assert_ne!(image_signature(400, 300, &a), image_signature(400, 300, &b));
        assert_ne!(
            image_signature(400, 300, &a),
            image_signature(300, 400, &a),
            "same bytes, other shape"
        );
    }

    #[test]
    fn pixels_to_png() {
        let png = rgba_png(2, 1, vec![255, 0, 0, 255, 0, 0, 255, 255]).unwrap();
        let img = image::load_from_memory(&png).unwrap().to_rgba8();
        assert_eq!(img.get_pixel(1, 0).0, [0, 0, 255, 255]);
        assert!(rgba_png(2, 2, vec![0; 4]).is_none(), "wrong size");
    }
}
