//! The system clipboard, for the history: what's on it, which app is in
//! front, and putting clips back. On macOS this talks to NSPasteboard
//! directly (text, images, files, and the markers password managers set);
//! elsewhere it falls back to text only through `arboard`.

use std::path::PathBuf;

/// What was on the clipboard at one moment.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Snapshot {
    /// Marked as private or temporary (passwords, one-time codes): never record.
    pub concealed: bool,
    pub files: Vec<PathBuf>,
    pub text: Option<String>,
    /// The image, normalised to PNG (so the same picture always hashes the same).
    pub image_png: Option<Vec<u8>>,
}

/// Pasteboard types that mark content as not to be recorded
/// (see nspasteboard.org), and password managers' own markers.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub const CONCEALED_TYPES: [&str; 6] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
];

/// Apps whose copies are never recorded, whatever they mark them as.
pub const IGNORED_APPS: [&str; 7] = [
    "com.apple.Passwords",
    "com.apple.keychainaccess",
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.bitwarden.desktop",
    "org.keepassxc.keepassxc",
    "com.dashlane.dashlanephonefinal",
];

/// One piece of a multi-clip.
#[derive(Debug, Clone, PartialEq)]
pub enum Part {
    Text(String),
    Png(Vec<u8>),
    File(PathBuf),
}

/// How several parts go onto the clipboard together.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Composed {
    /// All parts are files: put them on as files (Finder pastes them all).
    pub files: Vec<PathBuf>,
    /// Every text part (and file path), for plain-text fields.
    pub text: String,
    /// Text and images in order, for rich editors (Mail, Notes, Pages, docs
    /// in the browser).
    pub html: Option<String>,
    /// The first image, for apps that only take a picture.
    pub png: Option<Vec<u8>>,
}

pub fn compose(parts: &[Part]) -> Composed {
    if !parts.is_empty() && parts.iter().all(|p| matches!(p, Part::File(_))) {
        return Composed {
            files: parts
                .iter()
                .filter_map(|p| match p {
                    Part::File(f) => Some(f.clone()),
                    _ => None,
                })
                .collect(),
            ..Default::default()
        };
    }
    let texts: Vec<String> = parts
        .iter()
        .filter_map(|p| match p {
            Part::Text(t) => Some(t.trim_end().to_string()),
            Part::File(f) => Some(f.display().to_string()),
            Part::Png(_) => None,
        })
        .collect();
    let separator = if texts.iter().any(|t| t.contains('\n')) {
        "\n\n"
    } else {
        "\n"
    };
    let png = parts.iter().find_map(|p| match p {
        Part::Png(png) => Some(png.clone()),
        _ => None,
    });
    let html = (parts.len() > 1 || png.is_some()).then(|| {
        parts
            .iter()
            .map(|p| match p {
                Part::Text(t) => {
                    let t = t.trim();
                    if crate::capture::is_link(t) {
                        format!("<p><a href=\"{0}\">{0}</a></p>", html_escape(t))
                    } else {
                        format!("<p>{}</p>", html_escape(t).replace('\n', "<br>"))
                    }
                }
                Part::File(f) => format!("<p>{}</p>", html_escape(&f.display().to_string())),
                Part::Png(png) => {
                    format!("<p><img src=\"data:image/png;base64,{}\"></p>", base64(png))
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    });
    Composed {
        files: Vec::new(),
        text: texts.join(separator),
        html,
        png,
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn base64(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let n = chunk
            .iter()
            .enumerate()
            .fold(0u32, |n, (i, b)| n | (*b as u32) << (16 - 8 * i));
        for i in 0..4 {
            if i <= chunk.len() {
                out.push(ALPHABET[(n >> (18 - 6 * i) & 63) as usize] as char);
            } else {
                out.push('=');
            }
        }
    }
    out
}

/// Decode any image the `image` crate reads and re-encode it as PNG.
pub fn normalise_png(bytes: &[u8]) -> Option<Vec<u8>> {
    let img = image::load_from_memory(bytes).ok()?;
    let mut out = Vec::new();
    img.to_rgba8()
        .write_to(&mut std::io::Cursor::new(&mut out), image::ImageFormat::Png)
        .ok()?;
    Some(out)
}

#[cfg(target_os = "macos")]
mod imp {
    use super::*;
    use objc2::rc::Retained;
    use objc2::runtime::ProtocolObject;
    use objc2_app_kit::{
        NSPasteboard, NSPasteboardItem, NSPasteboardTypeFileURL, NSPasteboardTypeHTML,
        NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF, NSPasteboardWriting,
        NSWorkspace,
    };
    use objc2_foundation::{NSArray, NSData, NSString, NSURL};

    fn general() -> Retained<NSPasteboard> {
        NSPasteboard::generalPasteboard()
    }

    /// Increases every time anything is copied.
    pub fn change_count() -> isize {
        general().changeCount()
    }

    pub fn read() -> Snapshot {
        read_from(&general())
    }

    pub fn write_text(text: &str) -> bool {
        write_text_to(&general(), text)
    }

    pub fn write_png(png: &[u8]) -> bool {
        write_png_to(&general(), png)
    }

    pub fn write_files(paths: &[PathBuf]) -> bool {
        write_files_to(&general(), paths)
    }

    pub fn write_parts(parts: &[Part]) -> bool {
        write_parts_to(&general(), parts)
    }

    fn write_parts_to(pb: &NSPasteboard, parts: &[Part]) -> bool {
        let composed = compose(parts);
        if !composed.files.is_empty() {
            return write_files_to(pb, &composed.files);
        }
        pb.clearContents();
        let mut ok = false;
        if !composed.text.is_empty() {
            ok |= pb.setString_forType(&NSString::from_str(&composed.text), unsafe {
                NSPasteboardTypeString
            });
        }
        if let Some(html) = &composed.html {
            ok |= pb.setString_forType(&NSString::from_str(html), unsafe { NSPasteboardTypeHTML });
        }
        if let Some(png) = &composed.png {
            ok |= pb.setData_forType(Some(&NSData::with_bytes(png)), unsafe {
                NSPasteboardTypePNG
            });
        }
        ok
    }

    fn read_from(pb: &NSPasteboard) -> Snapshot {
        objc2::rc::autoreleasepool(|_| {
            let types: Vec<String> = pb
                .types()
                .map(|t| t.iter().map(|t| t.to_string()).collect())
                .unwrap_or_default();
            if types.iter().any(|t| CONCEALED_TYPES.contains(&t.as_str())) {
                return Snapshot {
                    concealed: true,
                    ..Default::default()
                };
            }

            let files: Vec<PathBuf> = pb
                .pasteboardItems()
                .map(|items| {
                    items
                        .iter()
                        .filter_map(|item| item.stringForType(unsafe { NSPasteboardTypeFileURL }))
                        .filter_map(|s| NSURL::URLWithString(&s))
                        .filter_map(|url| url.path())
                        .map(|p| PathBuf::from(p.to_string()))
                        .collect()
                })
                .unwrap_or_default();
            let text = pb
                .stringForType(unsafe { NSPasteboardTypeString })
                .map(|s| s.to_string());
            let image_png = [unsafe { NSPasteboardTypePNG }, unsafe {
                NSPasteboardTypeTIFF
            }]
            .into_iter()
            .find_map(|t| pb.dataForType(t))
            .and_then(|data| normalise_png(&data.to_vec()));
            Snapshot {
                concealed: false,
                files,
                text,
                image_png,
            }
        })
    }

    /// The name and bundle id of the app in front.
    pub fn frontmost_app() -> (Option<String>, Option<String>) {
        let app = NSWorkspace::sharedWorkspace().frontmostApplication();
        (
            app.as_ref()
                .and_then(|a| a.localizedName())
                .map(|s| s.to_string()),
            app.as_ref()
                .and_then(|a| a.bundleIdentifier())
                .map(|s| s.to_string()),
        )
    }

    fn write_text_to(pb: &NSPasteboard, text: &str) -> bool {
        pb.clearContents();
        pb.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString })
    }

    fn write_png_to(pb: &NSPasteboard, png: &[u8]) -> bool {
        pb.clearContents();
        pb.setData_forType(Some(&NSData::with_bytes(png)), unsafe {
            NSPasteboardTypePNG
        })
    }

    fn write_files_to(pb: &NSPasteboard, paths: &[PathBuf]) -> bool {
        let items: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = paths
            .iter()
            .filter_map(|p| {
                let url = NSURL::fileURLWithPath(&NSString::from_str(&p.to_string_lossy()));
                let link = url.absoluteString()?;
                let item = NSPasteboardItem::new();
                item.setString_forType(&link, unsafe { NSPasteboardTypeFileURL })
                    .then(|| ProtocolObject::from_retained(item))
            })
            .collect();
        pb.clearContents();
        !items.is_empty() && pb.writeObjects(&NSArray::from_retained_slice(&items))
    }

    /// Against a private pasteboard, so the tests never touch your clipboard.
    #[cfg(test)]
    mod tests {
        use super::*;

        struct Private(Retained<NSPasteboard>);
        impl Drop for Private {
            fn drop(&mut self) {
                // Not in the bindings; frees the private pasteboard's name.
                unsafe { objc2::msg_send![&*self.0, releaseGlobally] }
            }
        }
        fn private() -> Private {
            Private(NSPasteboard::pasteboardWithUniqueName())
        }

        #[test]
        fn text_round_trip_and_change_count() {
            let pb = private();
            let before = pb.0.changeCount();
            assert!(write_text_to(&pb.0, "héllo ✓"));
            assert!(pb.0.changeCount() > before);
            let snap = read_from(&pb.0);
            assert_eq!(snap.text.as_deref(), Some("héllo ✓"));
            assert!(!snap.concealed && snap.files.is_empty() && snap.image_png.is_none());
        }

        #[test]
        fn image_round_trip_is_normalised() {
            let pb = private();
            let mut jpeg = Vec::new();
            image::RgbImage::from_pixel(8, 6, image::Rgb([200, 30, 30]))
                .write_to(
                    &mut std::io::Cursor::new(&mut jpeg),
                    image::ImageFormat::Png,
                )
                .unwrap();
            assert!(write_png_to(&pb.0, &jpeg));
            let png = read_from(&pb.0).image_png.unwrap();
            let img = image::load_from_memory(&png).unwrap();
            assert_eq!((img.width(), img.height()), (8, 6));
            // Reading the same picture again gives the same bytes (one clip).
            assert!(write_png_to(&pb.0, &png));
            assert_eq!(read_from(&pb.0).image_png.unwrap(), png);
        }

        #[test]
        fn files_round_trip() {
            let pb = private();
            let dir = tempfile::tempdir().unwrap();
            let a = dir.path().join("a report.pdf");
            let b = dir.path().join("b.txt");
            std::fs::write(&a, b"x").unwrap();
            std::fs::write(&b, b"y").unwrap();
            assert!(write_files_to(&pb.0, &[a.clone(), b.clone()]));
            let files = read_from(&pb.0).files;
            let canon = |p: &PathBuf| std::fs::canonicalize(p).unwrap();
            assert_eq!(
                files.iter().map(canon).collect::<Vec<_>>(),
                [canon(&a), canon(&b)]
            );
        }

        #[test]
        fn parts_go_on_together() {
            let pb = private();
            let mut png = Vec::new();
            image::RgbImage::from_pixel(2, 2, image::Rgb([1, 2, 3]))
                .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
                .unwrap();
            assert!(write_parts_to(
                &pb.0,
                &[
                    Part::Text("Hello".into()),
                    Part::Png(png),
                    Part::Text("https://kwhorne.com".into())
                ]
            ));
            let snap = read_from(&pb.0);
            assert_eq!(snap.text.as_deref(), Some("Hello\nhttps://kwhorne.com"));
            assert!(snap.image_png.is_some());
            let html =
                pb.0.stringForType(unsafe { NSPasteboardTypeHTML })
                    .unwrap()
                    .to_string();
            assert!(html.contains("<p>Hello</p>"));
            assert!(html.contains("data:image/png;base64,"));
            assert!(html.contains("<a href=\"https://kwhorne.com\">"));
        }

        #[test]
        fn concealed_content_is_flagged() {
            let pb = private();
            pb.0.clearContents();
            pb.0.setString_forType(&NSString::from_str("hunter2"), unsafe {
                NSPasteboardTypeString
            });
            pb.0.setString_forType(
                &NSString::from_str(""),
                &NSString::from_str("org.nspasteboard.ConcealedType"),
            );
            let snap = read_from(&pb.0);
            assert!(snap.concealed);
            assert!(snap.text.is_none(), "nothing is read from it");
        }
    }
}

#[cfg(not(target_os = "macos"))]
mod imp {
    use super::*;
    use std::hash::{Hash, Hasher};

    /// A hash of the clipboard text stands in for a change counter.
    pub fn change_count() -> isize {
        let mut h = std::collections::hash_map::DefaultHasher::new();
        text().hash(&mut h);
        h.finish() as isize
    }

    fn text() -> Option<String> {
        arboard::Clipboard::new().ok()?.get_text().ok()
    }

    pub fn read() -> Snapshot {
        Snapshot {
            text: text(),
            ..Default::default()
        }
    }

    pub fn frontmost_app() -> (Option<String>, Option<String>) {
        (None, None)
    }

    pub fn write_text(text: &str) -> bool {
        arboard::Clipboard::new()
            .and_then(|mut c| c.set_text(text.to_string()))
            .is_ok()
    }

    pub fn write_png(png: &[u8]) -> bool {
        let Ok(img) = image::load_from_memory(png) else {
            return false;
        };
        let rgba = img.to_rgba8();
        let data = arboard::ImageData {
            width: rgba.width() as usize,
            height: rgba.height() as usize,
            bytes: rgba.into_raw().into(),
        };
        arboard::Clipboard::new()
            .and_then(|mut c| c.set_image(data))
            .is_ok()
    }

    pub fn write_files(_paths: &[PathBuf]) -> bool {
        false
    }

    pub fn write_parts(parts: &[Part]) -> bool {
        let composed = compose(parts);
        let text = if composed.files.is_empty() {
            composed.text
        } else {
            composed
                .files
                .iter()
                .map(|f| f.display().to_string())
                .collect::<Vec<_>>()
                .join("\n")
        };
        !text.is_empty() && write_text(&text)
    }
}

pub use imp::{change_count, frontmost_app, read, write_files, write_parts, write_png, write_text};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn composing_parts() {
        let files = compose(&[Part::File("/a.pdf".into()), Part::File("/b.txt".into())]);
        assert_eq!(files.files.len(), 2);
        assert!(files.text.is_empty() && files.html.is_none());

        let lines = compose(&[Part::Text("one".into()), Part::Text("two".into())]);
        assert_eq!(lines.text, "one\ntwo");
        assert_eq!(lines.html.as_deref(), Some("<p>one</p>\n<p>two</p>"));

        let blocks = compose(&[
            Part::Text("a\nb".into()),
            Part::Text("<c & d>".into()),
            Part::File("/x y.txt".into()),
        ]);
        assert_eq!(blocks.text, "a\nb\n\n<c & d>\n\n/x y.txt");
        let html = blocks.html.unwrap();
        assert!(html.contains("<p>a<br>b</p>"));
        assert!(html.contains("&lt;c &amp; d&gt;"));

        let single = compose(&[Part::Text("just this".into())]);
        assert_eq!(single.text, "just this");
        assert!(single.html.is_none());
    }

    #[test]
    fn base64_matches_the_standard() {
        assert_eq!(base64(b""), "");
        assert_eq!(base64(b"f"), "Zg==");
        assert_eq!(base64(b"fo"), "Zm8=");
        assert_eq!(base64(b"foo"), "Zm9v");
        assert_eq!(base64(b"foobar"), "Zm9vYmFy");
        assert_eq!(base64(&[0xff, 0xfe, 0x00]), "//4A");
    }
}
