//! The system clipboard, for the history: what's on it, which app is in
//! front, and putting clips back. On macOS this talks to NSPasteboard
//! directly (text, images, files, and the markers password managers set);
//! elsewhere it falls back to text only through `arboard`.

use std::path::PathBuf;

/// What was on the clipboard at one moment.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Snapshot {
    /// Marked as private or temporary (passwords, one-time codes): never record.
    pub concealed: bool,
    pub files: Vec<PathBuf>,
    pub text: Option<String>,
    /// The image, normalised to PNG (so the same picture always hashes the same).
    pub image_png: Option<Vec<u8>>,
}

/// Pasteboard types that mark content as not to be recorded
/// (see nspasteboard.org), and password managers' own markers.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub const CONCEALED_TYPES: [&str; 6] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
];

/// Apps whose copies are never recorded, whatever they mark them as.
pub const IGNORED_APPS: [&str; 7] = [
    "com.apple.Passwords",
    "com.apple.keychainaccess",
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.bitwarden.desktop",
    "org.keepassxc.keepassxc",
    "com.dashlane.dashlanephonefinal",
];

pub use xpress_core::clipboard::Part;

/// Decode any image the `image` crate reads and re-encode it as PNG.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub fn normalise_png(bytes: &[u8]) -> Option<Vec<u8>> {
    let img = image::load_from_memory(bytes).ok()?;
    let mut out = Vec::new();
    img.to_rgba8()
        .write_to(&mut std::io::Cursor::new(&mut out), image::ImageFormat::Png)
        .ok()?;
    Some(out)
}

#[cfg(target_os = "macos")]
mod imp {
    use super::*;
    use objc2::rc::Retained;
    use objc2_app_kit::{
        NSPasteboard, NSPasteboardTypeFileURL, NSPasteboardTypePNG, NSPasteboardTypeString,
        NSPasteboardTypeTIFF, NSWorkspace,
    };
    use objc2_foundation::NSURL;

    fn general() -> Retained<NSPasteboard> {
        NSPasteboard::generalPasteboard()
    }

    /// Increases every time anything is copied.
    pub fn change_count() -> isize {
        general().changeCount()
    }

    pub fn read() -> Snapshot {
        read_from(&general())
    }

    pub fn write(parts: &[Part]) -> bool {
        xpress_core::clipboard::write(parts)
    }

    fn read_from(pb: &NSPasteboard) -> Snapshot {
        objc2::rc::autoreleasepool(|_| {
            let types: Vec<String> = pb
                .types()
                .map(|t| t.iter().map(|t| t.to_string()).collect())
                .unwrap_or_default();
            if types.iter().any(|t| CONCEALED_TYPES.contains(&t.as_str())) {
                return Snapshot {
                    concealed: true,
                    ..Default::default()
                };
            }

            let files: Vec<PathBuf> = pb
                .pasteboardItems()
                .map(|items| {
                    items
                        .iter()
                        .filter_map(|item| item.stringForType(unsafe { NSPasteboardTypeFileURL }))
                        .filter_map(|s| NSURL::URLWithString(&s))
                        .filter_map(|url| url.path())
                        .map(|p| PathBuf::from(p.to_string()))
                        .collect()
                })
                .unwrap_or_default();
            let text = pb
                .stringForType(unsafe { NSPasteboardTypeString })
                .map(|s| s.to_string());
            let image_png = [unsafe { NSPasteboardTypePNG }, unsafe {
                NSPasteboardTypeTIFF
            }]
            .into_iter()
            .find_map(|t| pb.dataForType(t))
            .and_then(|data| normalise_png(&data.to_vec()));
            Snapshot {
                concealed: false,
                files,
                text,
                image_png,
            }
        })
    }

    /// The name and bundle id of the app in front.
    pub fn frontmost_app() -> (Option<String>, Option<String>) {
        let app = NSWorkspace::sharedWorkspace().frontmostApplication();
        (
            app.as_ref()
                .and_then(|a| a.localizedName())
                .map(|s| s.to_string()),
            app.as_ref()
                .and_then(|a| a.bundleIdentifier())
                .map(|s| s.to_string()),
        )
    }

    /// Against a private pasteboard, so the tests never touch your clipboard.
    #[cfg(test)]
    mod tests {
        use super::*;
        use objc2_app_kit::NSPasteboardTypeHTML;
        use objc2_foundation::NSString;
        use xpress_core::clipboard::write_to;

        struct Private(Retained<NSPasteboard>);
        impl Drop for Private {
            fn drop(&mut self) {
                // Not in the bindings; frees the private pasteboard's name.
                unsafe { objc2::msg_send![&*self.0, releaseGlobally] }
            }
        }
        fn private() -> Private {
            Private(NSPasteboard::pasteboardWithUniqueName())
        }

        #[test]
        fn text_round_trip_and_change_count() {
            let pb = private();
            let before = pb.0.changeCount();
            assert!(write_to(&pb.0, &[Part::Text("héllo ✓".into())]));
            assert!(pb.0.changeCount() > before);
            let snap = read_from(&pb.0);
            assert_eq!(snap.text.as_deref(), Some("héllo ✓"));
            assert!(!snap.concealed && snap.files.is_empty() && snap.image_png.is_none());
        }

        #[test]
        fn image_round_trip_is_normalised() {
            let pb = private();
            let mut jpeg = Vec::new();
            image::RgbImage::from_pixel(8, 6, image::Rgb([200, 30, 30]))
                .write_to(
                    &mut std::io::Cursor::new(&mut jpeg),
                    image::ImageFormat::Png,
                )
                .unwrap();
            assert!(write_to(&pb.0, &[Part::Png(jpeg)]));
            let png = read_from(&pb.0).image_png.unwrap();
            let img = image::load_from_memory(&png).unwrap();
            assert_eq!((img.width(), img.height()), (8, 6));
            // Reading the same picture again gives the same bytes (one clip).
            assert!(write_to(&pb.0, &[Part::Png(png.clone())]));
            assert_eq!(read_from(&pb.0).image_png.unwrap(), png);
        }

        #[test]
        fn files_round_trip() {
            let pb = private();
            let dir = tempfile::tempdir().unwrap();
            let a = dir.path().join("a report.pdf");
            let b = dir.path().join("b.txt");
            std::fs::write(&a, b"x").unwrap();
            std::fs::write(&b, b"y").unwrap();
            assert!(write_to(
                &pb.0,
                &[Part::File(a.clone()), Part::File(b.clone())]
            ));
            let files = read_from(&pb.0).files;
            let canon = |p: &PathBuf| std::fs::canonicalize(p).unwrap();
            assert_eq!(
                files.iter().map(canon).collect::<Vec<_>>(),
                [canon(&a), canon(&b)]
            );
        }

        #[test]
        fn parts_go_on_together() {
            let pb = private();
            let mut png = Vec::new();
            image::RgbImage::from_pixel(2, 2, image::Rgb([1, 2, 3]))
                .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
                .unwrap();
            assert!(write_to(
                &pb.0,
                &[
                    Part::Text("Hello".into()),
                    Part::Png(png),
                    Part::Text("https://kwhorne.com".into())
                ]
            ));
            let snap = read_from(&pb.0);
            assert_eq!(snap.text.as_deref(), Some("Hello\nhttps://kwhorne.com"));
            assert!(snap.image_png.is_some());
            let html =
                pb.0.stringForType(unsafe { NSPasteboardTypeHTML })
                    .unwrap()
                    .to_string();
            assert!(html.contains("<p>Hello</p>"));
            assert!(html.contains("data:image/png;base64,"));
            assert!(html.contains("<a href=\"https://kwhorne.com\">"));
        }

        #[test]
        fn concealed_content_is_flagged() {
            let pb = private();
            pb.0.clearContents();
            pb.0.setString_forType(&NSString::from_str("hunter2"), unsafe {
                NSPasteboardTypeString
            });
            pb.0.setString_forType(
                &NSString::from_str(""),
                &NSString::from_str("org.nspasteboard.ConcealedType"),
            );
            let snap = read_from(&pb.0);
            assert!(snap.concealed);
            assert!(snap.text.is_none(), "nothing is read from it");
        }
    }
}

#[cfg(not(target_os = "macos"))]
mod imp {
    use super::*;
    use std::hash::{Hash, Hasher};

    /// A hash of the clipboard text stands in for a change counter.
    pub fn change_count() -> isize {
        let mut h = std::collections::hash_map::DefaultHasher::new();
        text().hash(&mut h);
        h.finish() as isize
    }

    fn text() -> Option<String> {
        arboard::Clipboard::new().ok()?.get_text().ok()
    }

    pub fn read() -> Snapshot {
        Snapshot {
            text: text(),
            ..Default::default()
        }
    }

    pub fn frontmost_app() -> (Option<String>, Option<String>) {
        (None, None)
    }

    /// Text only here (images as text would be wrong; files have no path form).
    pub fn write(parts: &[Part]) -> bool {
        let composed = xpress_core::clipboard::compose(parts);
        let text = if composed.files.is_empty() {
            composed.text
        } else {
            composed
                .files
                .iter()
                .map(|f| f.display().to_string())
                .collect::<Vec<_>>()
                .join("\n")
        };
        if !text.is_empty() {
            return arboard::Clipboard::new()
                .and_then(|mut c| c.set_text(text))
                .is_ok();
        }
        let Some(png) = composed.png else {
            return false;
        };
        let Ok(img) = image::load_from_memory(&png) else {
            return false;
        };
        let rgba = img.to_rgba8();
        let data = arboard::ImageData {
            width: rgba.width() as usize,
            height: rgba.height() as usize,
            bytes: rgba.into_raw().into(),
        };
        arboard::Clipboard::new()
            .and_then(|mut c| c.set_image(data))
            .is_ok()
    }
}

pub use imp::{change_count, frontmost_app, read, write};
