# These are supported funding model platforms. Uncomment/fill the ones you use.
github: [kwhorne]
# ko_fi: your_handle
# buy_me_a_coffee: your_handle
# patreon: your_handle
# liberapay: your_handle
# custom: ["https://example.com/donate"]
